services:
  - type: web
    name: turismo-nacional-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
